--------------------------------------------------------
--  DDL for Table ADDRESS
--------------------------------------------------------

  CREATE TABLE "RESIDENT"."ADDRESS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"PROVINCE" VARCHAR2(5 BYTE), 
	"DISTRICT" VARCHAR2(5 BYTE), 
	"STREET" VARCHAR2(20 BYTE), 
	"HOST" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADDRESS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESIDENT"."ADDRESS_PK" ON "RESIDENT"."ADDRESS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ADDRESS
--------------------------------------------------------

  ALTER TABLE "RESIDENT"."ADDRESS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."ADDRESS" MODIFY ("PROVINCE" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."ADDRESS" MODIFY ("DISTRICT" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."ADDRESS" MODIFY ("STREET" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."ADDRESS" MODIFY ("HOST" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."ADDRESS" ADD CONSTRAINT "ADDRESS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
