--------------------------------------------------------
--  DDL for Table PERSON
--------------------------------------------------------

  CREATE TABLE "RESIDENT"."PERSON" 
   (	"PERSONNUMBER" VARCHAR2(20 BYTE), 
	"FULLNAME" VARCHAR2(50 BYTE), 
	"BIRTHDAY" DATE, 
	"BIRTHPLACE" VARCHAR2(5 BYTE), 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"RELIGION" VARCHAR2(5 BYTE), 
	"NATION" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PERSON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESIDENT"."PERSON_PK" ON "RESIDENT"."PERSON" ("PERSONNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "RESIDENT"."PERSON" MODIFY ("PERSONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."PERSON" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."PERSON" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."PERSON" MODIFY ("BIRTHPLACE" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("PERSONNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSON
--------------------------------------------------------

  ALTER TABLE "RESIDENT"."PERSON" ADD CONSTRAINT "BIRTHPLACE_PROVINCE_FK" FOREIGN KEY ("BIRTHPLACE")
	  REFERENCES "RESIDENT"."PROVINCE" ("PROVINCEID") ENABLE;
  ALTER TABLE "RESIDENT"."PERSON" ADD CONSTRAINT "RELIGION_RELIGION_FK" FOREIGN KEY ("RELIGION")
	  REFERENCES "RESIDENT"."RELIGION" ("RELIGIONID") ENABLE;
  ALTER TABLE "RESIDENT"."PERSON" ADD CONSTRAINT "NATION_NATION_FK" FOREIGN KEY ("NATION")
	  REFERENCES "RESIDENT"."NATION" ("NATIONID") ENABLE;
