--------------------------------------------------------
--  DDL for Table PROVINCE
--------------------------------------------------------

  CREATE TABLE "RESIDENT"."PROVINCE" 
   (	"PROVINCEID" VARCHAR2(5 BYTE), 
	"PROVINCENAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVINCE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESIDENT"."PROVINCE_PK" ON "RESIDENT"."PROVINCE" ("PROVINCEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PROVINCE
--------------------------------------------------------

  ALTER TABLE "RESIDENT"."PROVINCE" MODIFY ("PROVINCEID" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."PROVINCE" MODIFY ("PROVINCENAME" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."PROVINCE" ADD CONSTRAINT "PROVINCE_PK" PRIMARY KEY ("PROVINCEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
