--------------------------------------------------------
--  DDL for Table RELIGION
--------------------------------------------------------

  CREATE TABLE "RESIDENT"."RELIGION" 
   (	"RELIGIONID" VARCHAR2(5 BYTE), 
	"RELIGIONNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RELIGION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESIDENT"."RELIGION_PK" ON "RESIDENT"."RELIGION" ("RELIGIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RELIGION
--------------------------------------------------------

  ALTER TABLE "RESIDENT"."RELIGION" MODIFY ("RELIGIONID" NOT NULL ENABLE);
  ALTER TABLE "RESIDENT"."RELIGION" ADD CONSTRAINT "RELIGION_PK" PRIMARY KEY ("RELIGIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
