INSERT INTO STATE VALUES ('CN', 'Chờ nộp');
INSERT INTO STATE VALUES ('CXT', 'Chờ xác thực');
INSERT INTO STATE VALUES ('CD', 'Chờ duyệt');
INSERT INTO STATE VALUES ('DD', 'Đã duyệt');
INSERT INTO STATE VALUES ('CL', 'Chờ lưu');
INSERT INTO STATE VALUES ('DL', 'Đã lưu');
INSERT INTO STATE VALUES ('KD', 'Không duyệt');
INSERT INTO STATE VALUES ('KXT', 'Không xác thực');

INSERT INTO TASK VALUES ('LD', 'Lần đầu');

INSERT INTO RELIGION VALUES ('BD','Bản địa');
INSERT INTO RELIGION VALUES ('PG','Phật Giáo');
INSERT INTO RELIGION VALUES ('CG','Công Giáo');
INSERT INTO RELIGION VALUES ('TL','Tin Lành');
INSERT INTO RELIGION VALUES ('HH','Hòa Hảo');
INSERT INTO RELIGION VALUES ('CD','Cao Đài');
INSERT INTO RELIGION VALUES ('DG','Đạo Giáo');
INSERT INTO RELIGION VALUES ('NG','Nho Giáo');
INSERT INTO RELIGION VALUES ('HG','Hồi Giáo');


