--------------------------------------------------------
--  DDL for Table DISTRICT
--------------------------------------------------------

  CREATE TABLE "PASSPORT"."DISTRICT" 
   (	"PROVINCEID" VARCHAR2(5 BYTE), 
	"DISTRICTID" VARCHAR2(5 BYTE), 
	"DISTRICTNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DISTRICT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PASSPORT"."DISTRICT_PK" ON "PASSPORT"."DISTRICT" ("PROVINCEID", "DISTRICTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DISTRICT
--------------------------------------------------------

  ALTER TABLE "PASSPORT"."DISTRICT" MODIFY ("PROVINCEID" NOT NULL ENABLE);
  ALTER TABLE "PASSPORT"."DISTRICT" MODIFY ("DISTRICTID" NOT NULL ENABLE);
  ALTER TABLE "PASSPORT"."DISTRICT" MODIFY ("DISTRICTNAME" NOT NULL ENABLE);
  ALTER TABLE "PASSPORT"."DISTRICT" ADD CONSTRAINT "DISTRICT_PK" PRIMARY KEY ("PROVINCEID", "DISTRICTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DISTRICT
--------------------------------------------------------

  ALTER TABLE "PASSPORT"."DISTRICT" ADD CONSTRAINT "DISTRICT_PROVINCE_FK" FOREIGN KEY ("PROVINCEID")
	  REFERENCES "PASSPORT"."PROVINCE" ("PROVINCEID") ON DELETE CASCADE ENABLE;
